apiVersion: v1
kind: Pod
metadata:
  name: cd-test
  namespace: dev
spec:
  containers:
  - name: echoserver
    image: gcr.io/google_containers/echoserver:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080